#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 Alex.K.
"""Verifies a generated ESP-IDF `sdkconfig` file against the approved
production security profile (plan S5 required change #3).

This is a pure text-parsing/comparison tool: it takes whatever `sdkconfig`
`idf.py` already generated (a plain `CONFIG_X=value` / `# CONFIG_X is not
set` text file) and fails loudly on any symbol that is missing, has the
wrong value, or is a known-insecure development flag that must never be
present in a production build.

It does NOT invoke ESP-IDF itself and does not know whether the values it
is checking actually correspond to real, working hardware security
features on the target chip -- that can only be confirmed by an actual
`idf.py build` plus Secure Boot/Flash Encryption/NVS Encryption readback
on real ESP32-C6 hardware (plan S5's Target/HIL test list), which this
script cannot perform in a host-only environment.

The exact approved Kconfig symbol names below were verified two ways: (1)
against the official ESP-IDF 5.5.1 documentation for ESP32-C6 (Security
Features Enablement Workflows, Secure Boot v2, Configuration Options
Reference), and (2) directly against the real Kconfig source inside the
`espressif/idf:release-v5.5` Docker image (which resolves to ESP-IDF
5.5.5, not exactly the plan's pinned 5.5.2 -- see
docs/security/PRODUCTION_HARDENING.md Section 2.3 for that discrepancy),
by actually running `idf.py set-target esp32c6` with this repository's
layered sdkconfig.defaults files and inspecting the generated `sdkconfig`.
That pass caught and fixed two real mistakes a docs-only pass had missed:
`CONFIG_ESP32C6_DISABLE_JTAG` (web-search-sourced) does not exist anywhere
in ESP-IDF 5.5's Kconfig tree -- the real symbol is
`CONFIG_SECURE_BOOT_ALLOW_JTAG`; and `CONFIG_SECURE_BOOT_INSECURE` (the
master gate for the entire "Potentially Insecure" Kconfig menu, which
`SECURE_BOOT_ALLOW_JTAG` lives inside) was missing from the forbidden list
entirely. See docs/security/PRODUCTION_HARDENING.md Section 2 for the
full verification trail.

Optionally (plan #4's second half) this script also checks the resolved
ESP-IDF version, sourced from a real build's `project_description.json`
(`--project-description PATH`, generated by `idf.py reconfigure`/`build`
-- its `git_revision` field is ESP-IDF's own `git describe` output for
whatever IDF_PATH checkout actually produced the build, e.g.
`v5.5.5-316-g1a1a5aa6513`, so this check is tied to the real build rather
than a static, possibly-stale copy of ESP-IDF's version.cmake). This
project's own CI tracks the `espressif/idf:release-v5.5` image tag, which
follows Espressif's 5.5.x release branch rather than a single frozen
patch (confirmed to currently resolve to 5.5.5, not the plan's originally
written "exactly 5.5.2") -- so the check enforces MAJOR.MINOR == 5.5 and
deliberately allows any PATCH, matching how this project's CI actually
consumes ESP-IDF. Skipping `--project-description` skips the version
check entirely (e.g. when only a bare sdkconfig is available, with no
accompanying build directory).

Also checks plan S6's ten FD-13 bounded tunables (`main/Kconfig.projbuild`'s
"Security" submenu, `components/service/include/security_bounds.hpp`'s own
range table -- the same (minimum, maximum, approved_default) triples are
declared in exactly one place in this script, `TUNABLE_RANGES` below, and
independently in the C++ accessor; keeping both in sync is a named,
tracked responsibility, not automated). Per the plan's own text ("An
in-range change from the approved default requires a reviewed
release-manifest delta... rather than an automatic rejection solely for
differing from the default"), this only rejects a value OUTSIDE
[minimum, maximum] -- not a value that merely differs from the approved
default.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from typing import Dict, List, Optional, Tuple

# This project's CI tracks the espressif/idf:release-v5.5 image tag (a
# branch-tracking tag that follows Espressif's 5.5.x patch releases), which
# currently resolves to 5.5.5 -- not the plan's originally written "exactly
# 5.5.2". MAJOR.MINOR is pinned; PATCH is deliberately unconstrained so this
# check tracks what the project's real CI configuration actually consumes
# rather than a single frozen patch that would immediately go stale. See
# docs/security/PRODUCTION_HARDENING.md Section 2.3/2.7 for the full
# discrepancy history.
EXPECTED_IDF_VERSION_MAJOR = 5
EXPECTED_IDF_VERSION_MINOR = 5

_GIT_REVISION_VERSION_RE = re.compile(r"^v?(\d+)\.(\d+)\.(\d+)")

# Symbols that MUST be present with exactly this value in a production
# sdkconfig. Each entry: (symbol, required_value, plan_item_reference).
REQUIRED_SYMBOLS: List[tuple] = [
    ("CONFIG_SECURE_BOOT", "y", "Secure Boot v2 (#1)"),
    ("CONFIG_SECURE_BOOT_V2_ENABLED", "y", "Secure Boot v2 (#1)"),
    ("CONFIG_SECURE_FLASH_ENC_ENABLED", "y", "Flash Encryption (#1)"),
    ("CONFIG_SECURE_FLASH_ENCRYPTION_MODE_RELEASE", "y", "Flash Encryption release mode (#1)"),
    ("CONFIG_NVS_ENCRYPTION", "y", "NVS Encryption (#1)"),
    ("CONFIG_NVS_SEC_KEY_PROTECT_USING_FLASH_ENC", "y", "NVS Encryption key scheme (#1)"),
    ("CONFIG_BOOTLOADER_APP_ROLLBACK_ENABLE", "y", "OTA app rollback (#1)"),
    ("CONFIG_BOOTLOADER_APP_ANTI_ROLLBACK", "y", "Secure-version anti-rollback (#1)"),
    ("CONFIG_SECURE_ENABLE_SECURE_ROM_DL_MODE", "y", "UART ROM download mode permanently switched to Secure mode (#1)"),
    (
        "CONFIG_ZGW_PRODUCTION_PROFILE",
        "y",
        "S6 ProvisioningSecretProvider adapter selection (#2) -- if unset, a 'production' build would "
        "silently fall back to the development PoP adapter instead of failing closed",
    ),
]

# Symbols that MUST NOT be "y" in a production sdkconfig -- each one is a
# real, named insecure/development-only escape hatch, not a made-up
# placeholder (#2: "insecure development flags are forbidden in
# production"). Verified against real ESP-IDF 5.5 Kconfig source, not
# memory or web search alone -- see the module docstring.
FORBIDDEN_SYMBOLS: List[tuple] = [
    (
        "CONFIG_SECURE_BOOT_BUILD_SIGNED_BINARIES",
        "external signing keeps the production private key out of the repository/CI (plan S5 #8)",
    ),
    (
        "CONFIG_SECURE_BOOT_INSECURE",
        "the master gate for ESP-IDF's entire 'Potentially Insecure' Kconfig menu "
        "(SECURE_BOOT_ALLOW_JTAG and others live inside it)",
    ),
    (
        "CONFIG_SECURE_BOOT_ALLOW_JTAG",
        "leaves JTAG enabled once Secure Boot/Flash Encryption are on, defeating both -- "
        "this is the real symbol; CONFIG_ESP32C6_DISABLE_JTAG (an earlier, web-search-sourced "
        "guess) does not exist in ESP-IDF 5.5 at all",
    ),
    (
        "CONFIG_SECURE_FLASH_ENCRYPTION_MODE_DEVELOPMENT",
        "Development mode allows re-flashing plaintext and must never appear alongside a "
        "production profile (the required CONFIG_SECURE_FLASH_ENCRYPTION_MODE_RELEASE=y above "
        "already implies this by Kconfig choice-exclusivity, but a real generated sdkconfig is "
        "checked explicitly here too for a clearer diagnostic if something is inconsistent)",
    ),
    (
        "CONFIG_ESP_COREDUMP_CAPTURE_DRAM",
        "plan S5 #14 ('Redact all key/credential material from logs, crash reports and "
        "completion evidence'): this symbol's own Kconfig help text reads 'Include whole .bss "
        "and .data sections and heap data into core dump file' -- exactly the memory regions "
        "where secret-namespace values (Wi-Fi credentials today, TLS keys/manufacturing PoP "
        "once populated) live at runtime. ESP-IDF's own default is already 'n' (unset), so this "
        "entry catches a future accidental opt-in, not a currently-enabled default",
    ),
]

# Plan S6, "Security invariants, bounded tunables and typed accessors":
# (symbol, minimum, maximum, approved_default, plan_ref). Kept in sync by
# hand with components/service/include/security_bounds.hpp's own
# kRanges table and main/Kconfig.projbuild's "Security" submenu -- all
# three declare the same ten (minimum, maximum, approved_default) triples,
# a named, tracked responsibility (see this script's module docstring).
TUNABLE_RANGES: List[tuple] = [
    ("CONFIG_ZGW_COMMISSIONING_WINDOW_SECONDS", 60, 600, 600, "S6 commissioning window"),
    ("CONFIG_ZGW_JSON_MAX_BODY_BYTES", 512, 2048, 2048, "S6 strict JSON reader body limit"),
    ("CONFIG_ZGW_JSON_MAX_DEPTH", 2, 4, 4, "S6 strict JSON reader depth limit"),
    ("CONFIG_ZGW_JSON_MAX_STRING_BYTES", 64, 512, 512, "S6 strict JSON reader string limit"),
    ("CONFIG_ZGW_JSON_MAX_KEYS", 8, 32, 32, "S6 strict JSON reader key-count limit"),
    ("CONFIG_ZGW_LOGIN_ATTEMPTS_PER_MINUTE", 1, 5, 5, "S6 login rate limit"),
    ("CONFIG_ZGW_COMMANDS_PER_MINUTE", 10, 60, 60, "S6 ordinary-command rate limit"),
    ("CONFIG_ZGW_MUTATIONS_PER_MINUTE", 1, 5, 5, "S6 mutation rate limit"),
    ("CONFIG_ZGW_FIRMWARE_OPS_PER_HOUR", 1, 2, 2, "S6 OTA/RCP rate limit"),
    ("CONFIG_ZGW_AUDIT_RING_RECORDS", 32, 128, 128, "S6 audit ring capacity"),
]


def parse_sdkconfig(text: str) -> Dict[str, Optional[str]]:
    """Parses `CONFIG_X=value` and `# CONFIG_X is not set` lines.

    Returns a dict mapping symbol name -> value string, or None for a
    symbol explicitly recorded as "not set". A symbol entirely absent from
    the dict was not mentioned in the file at all (distinct from
    explicitly "not set" -- both mean "not enabled", but only the second
    is what a real generated sdkconfig actually emits for every known
    boolean symbol; a symbol missing entirely usually means the Kconfig
    option didn't exist for this target/IDF version at all, which is
    itself worth flagging separately).
    """
    result: Dict[str, Optional[str]] = {}
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if line.startswith("# ") and line.endswith(" is not set"):
            symbol = line[2:-len(" is not set")]
            if symbol.startswith("CONFIG_"):
                result[symbol] = None
            continue
        if line.startswith("#"):
            continue
        if "=" not in line:
            continue
        symbol, _, value = line.partition("=")
        symbol = symbol.strip()
        value = value.strip()
        if len(value) >= 2 and value[0] == '"' and value[-1] == '"':
            value = value[1:-1]
        if symbol.startswith("CONFIG_"):
            result[symbol] = value
    return result


def verify_profile(config: Dict[str, Optional[str]]) -> List[str]:
    """Returns a list of human-readable violation strings; empty = pass."""
    violations: List[str] = []

    for symbol, required_value, plan_ref in REQUIRED_SYMBOLS:
        actual = config.get(symbol, "<absent from generated sdkconfig>")
        if actual is None:
            actual = "not set"
        if actual != required_value:
            violations.append(
                f"{symbol} must be '{required_value}' ({plan_ref}), found '{actual}'")

    for symbol, reason in FORBIDDEN_SYMBOLS:
        actual = config.get(symbol)
        if actual == "y":
            violations.append(f"{symbol} must not be set in production -- {reason}")

    violations.extend(verify_tunable_ranges(config))

    return violations


def verify_tunable_ranges(config: Dict[str, Optional[str]]) -> List[str]:
    """Plan S6: "Kconfig rejects out-of-range values. The production
    verifier ... verifies tunable range membership." Rejects a tunable
    that is absent, unparseable, or outside [minimum, maximum] -- but NOT
    one that is merely non-default, per the plan's own explicit
    "an in-range change from the approved default" carve-out.
    """
    violations: List[str] = []
    for symbol, minimum, maximum, _default, plan_ref in TUNABLE_RANGES:
        raw_value = config.get(symbol, "<absent from generated sdkconfig>")
        if raw_value is None:
            violations.append(f"{symbol} must be set to an integer in [{minimum}, {maximum}] ({plan_ref}), "
                               f"found 'not set'")
            continue
        try:
            value = int(raw_value)
        except (TypeError, ValueError):
            violations.append(f"{symbol} must be an integer in [{minimum}, {maximum}] ({plan_ref}), "
                               f"found '{raw_value}' (not parseable as an integer)")
            continue
        if value < minimum or value > maximum:
            violations.append(f"{symbol} must be in [{minimum}, {maximum}] ({plan_ref}), found {value}")
    return violations


def parse_idf_version(git_revision: str) -> Optional[Tuple[int, int, int]]:
    """Parses ESP-IDF's own `git describe`-style `git_revision` string, e.g.
    `v5.5.5-316-g1a1a5aa6513` (real ESP-IDF 5.5.5 output, `--dirty`-suffixed
    variants included) or a plain `v5.5.2`. Returns (major, minor, patch),
    or None if the string doesn't start with a recognizable `vX.Y.Z`.
    """
    match = _GIT_REVISION_VERSION_RE.match(git_revision.strip())
    if not match:
        return None
    return (int(match.group(1)), int(match.group(2)), int(match.group(3)))


def read_idf_version_from_project_description(path: str) -> Tuple[Optional[Tuple[int, int, int]], str]:
    """Reads a real `idf.py reconfigure`/`build`-generated
    `project_description.json` and extracts the resolved ESP-IDF version
    from its `git_revision` field -- this is ESP-IDF's own `git describe`
    output for whatever IDF_PATH checkout actually produced the build, so
    it reflects the real toolchain a build used, not a static file that
    could point at a different/stale ESP-IDF checkout.

    Returns (parsed_version_or_None, raw_git_revision_string_for_diagnostics).
    Raises OSError/ValueError/KeyError on a missing/unreadable/malformed
    file -- the caller is expected to turn that into an exit-code-2 error,
    matching how a missing sdkconfig is already handled.
    """
    with open(path, "r", encoding="utf-8") as handle:
        data = json.load(handle)
    git_revision = data["git_revision"]
    return parse_idf_version(git_revision), git_revision


def verify_idf_version(version: Optional[Tuple[int, int, int]], raw_git_revision: str) -> List[str]:
    """Returns a list of human-readable violation strings; empty = pass.

    Enforces MAJOR.MINOR == 5.5 (this project's actual CI configuration,
    espressif/idf:release-v5.5 -- see EXPECTED_IDF_VERSION_MAJOR/MINOR's
    module-level comment) and deliberately allows any PATCH.
    """
    if version is None:
        return [
            f"could not parse an ESP-IDF version out of git_revision {raw_git_revision!r} "
            "(expected a 'vMAJOR.MINOR.PATCH...' prefix)"
        ]
    major, minor, _patch = version
    if (major, minor) != (EXPECTED_IDF_VERSION_MAJOR, EXPECTED_IDF_VERSION_MINOR):
        return [
            f"resolved ESP-IDF version {raw_git_revision!r} is not "
            f"{EXPECTED_IDF_VERSION_MAJOR}.{EXPECTED_IDF_VERSION_MINOR}.x "
            f"(this project's CI tracks the espressif/idf:release-v5.5 image tag; "
            f"any patch level is accepted, but the major.minor must match)"
        ]
    return []


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("sdkconfig_path", help="Path to a generated ESP-IDF sdkconfig file")
    parser.add_argument(
        "--project-description",
        dest="project_description_path",
        default=None,
        help=(
            "Optional path to a real idf.py-generated project_description.json "
            "(same build directory as sdkconfig_path). When given, also verifies "
            "the resolved ESP-IDF version is 5.5.x (plan #4, second half). "
            "Omit to skip the version check entirely."
        ),
    )
    args = parser.parse_args(argv)

    try:
        with open(args.sdkconfig_path, "r", encoding="utf-8") as handle:
            text = handle.read()
    except OSError as error:
        print(f"error: cannot read {args.sdkconfig_path}: {error}", file=sys.stderr)
        return 2

    config = parse_sdkconfig(text)
    violations = verify_profile(config)

    if args.project_description_path is not None:
        try:
            version, raw_git_revision = read_idf_version_from_project_description(
                args.project_description_path)
        except (OSError, ValueError, KeyError) as error:
            print(f"error: cannot read {args.project_description_path}: {error}", file=sys.stderr)
            return 2
        violations.extend(verify_idf_version(version, raw_git_revision))

    if violations:
        print(f"FAILED: {args.sdkconfig_path} does not match the approved production security profile:")
        for violation in violations:
            print(f"  - {violation}")
        return 1

    print(f"OK: {args.sdkconfig_path} matches the approved production security profile.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
